issuersRecord: {
    baseUrl = "http://gateway:8000/v1/issuance"
    trustRecordPath = "<path>"
    governanceRecordPath = "<path>"
}
verifiersRecord: {
    baseUrl = "http://gateway:8000/v1/verifier"
    trustRecordPath = "<path>"
    governanceRecordPath = "<path>"
}