"""Public-safe contract for fixed EUDI runtime diagnostic categories."""

from __future__ import annotations

EUDI_RUNTIME_DIAGNOSTIC_SCHEMA = "elevenid.eudi-runtime-diagnostics/v1"

MDOC_DEVICE_AUTH_ERROR_KINDS = frozenset(
    {
        "detached-issuer-auth",
        "device-response-parse-failed",
        "session-transcript-parse-failed",
        "device-response-status-invalid",
        "device-response-documents-missing",
        "device-response-version-unsupported",
        "mso-parse-failed",
        "device-key-coordinates-missing",
        "device-key-type-unsupported",
        "device-auth-method-unsupported",
        "device-signature-invalid",
        "device-signature-processing-error",
        "device-signature-malformed",
        "device-signature-algorithm-mismatch",
        "device-key-invalid",
        "device-auth-cbor-error",
        "issuer-disclosure-digest-mismatch",
        "issuer-disclosure-commitment-missing",
        "issuer-certificate-profile-invalid",
        "issuer-algorithm-unprotected",
        "issuer-algorithm-unsupported",
        "mso-document-type-mismatch",
        "mso-validity-contradictory",
        "mso-not-yet-valid",
        "mso-expired",
        "unclassified",
    }
)

EUDI_RUNTIME_DIAGNOSTIC_CATEGORIES = frozenset(
    {
        "tls-trust",
        "hostname-resolution",
        "connect-failure",
        "metadata-deserialization",
        "metadata-missing-required-field",
        "metadata-json-type-mismatch",
        "metadata-field-credential-configurations-supported",
        "metadata-field-credential-definition",
        "metadata-field-cryptographic-binding-methods",
        "metadata-field-proof-types",
        "metadata-field-signing-algorithms",
        "metadata-field-claims",
        "metadata-field-doctype",
        "metadata-field-vct",
        "credential-offer",
        "invalid-proof",
        "invalid-nonce",
        "unsupported-format",
        "issuer-profile",
        "issuer-profile-not-found",
        "issuer-profile-binding-incomplete",
        "issuer-profile-identity-mismatch",
        "issuer-profile-algorithm-mismatch",
        "mdoc-namespace",
        "mdoc-certificate-chain",
        "mdoc-signature-missing",
        "mdoc-signature-length",
        "mdoc-signature-encoding",
        "mdoc-signature-der",
        "mdoc-claims",
        "mdoc-prepare",
        "mdoc-assemble",
        "mdoc-credential-id-mismatch",
        "upstream-http-4xx",
        "upstream-http-5xx",
        "verifier-invalid-request",
        "verifier-invalid-vp-token",
        "verifier-presentation-submission",
        "verifier-dcql",
        "verifier-vct",
        "verifier-key-binding",
        "marty-sd-jwt-verification",
        "marty-sd-jwt-issuer-key",
        "marty-sd-jwt-holder-key",
        "marty-sd-jwt-key-binding-required",
        "marty-sd-jwt-key-binding-signature",
        "marty-sd-jwt-signature",
        "marty-sd-jwt-key-binding-sd-hash",
        "marty-sd-jwt-key-binding-audience",
        "marty-sd-jwt-key-binding-nonce",
        "marty-sd-jwt-key-binding-freshness",
        "marty-sd-jwt-key-binding-header",
        "marty-sd-jwt-issuer-validity",
        "marty-sd-jwt-disclosure",
        "marty-sd-jwt-native-backend",
        "marty-mdoc-device-authentication",
        "marty-mdoc-session-transcript",
        "marty-mdoc-issuer-signature",
        "marty-mdoc-issuer-trust",
        "marty-mdoc-parse",
        "runtime-log-unavailable",
        "unclassified-runtime-failure",
    }
    | {f"marty-mdoc-error-kind-{kind}" for kind in MDOC_DEVICE_AUTH_ERROR_KINDS}
)
